// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// ProduceMessage provides a mock function with given fields: ctx, message, app, comment
func (_m *Producer) ProduceMessage(ctx context.Context, message protoreflect.ProtoMessage, app string, comment string) error {
	ret := _m.Called(ctx, message, app, comment)

	if len(ret) == 0 {
		panic("no return value specified for ProduceMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, string, string) error); ok {
		r0 = rf(ctx, message, app, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
